In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("data.csv")

In [17]:
df

     Name   Class  Marks School Result
0     Sonu   10th     76    USS   Pass
1     Monu  12th      87    FIS   Pass
2  Shivani   11th     33    GIS   Fail
3     Raju   9th      54  USSIS   Pass
4    Vikey  11th      76   GBSS   Pass
5    Vijay  11th      24   SKVS   Fail
6    Raja   11th      54    JUS   Pass
7    Guddu   10th     99    HUS   Pass
8   Ashish  12th      78   SUIS   Pass
9    Rohan  12th      87   LOIS   Pass

In [18]:
df = df[df["Marks"]>70]

In [19]:
df

    Name   Class  Marks School Result
0    Sonu   10th     76    USS   Pass
1    Monu  12th      87    FIS   Pass
4   Vikey  11th      76   GBSS   Pass
7   Guddu   10th     99    HUS   Pass
8  Ashish  12th      78   SUIS   Pass
9   Rohan  12th      87   LOIS   Pass

In [22]:
df.to_csv("data_updated.csv", index = False)