In [5]:
import pandas as pd

In [6]:
s1 = pd.Series([78, 98, 67, 78, 87, 87, 95])

In [7]:
print(s1)

0    78
1    98
2    67
3    78
4    87
5    87
6    95
dtype: int64

In [8]:
type(s1)

pandas.core.series.Series

In [9]:
s2 = pd.Series([78, 98, 67, 78, 87, 87, 95], index=["SONU", "MONI", "RADHA", "VIRAT", "SHAAM", "VIJAY", "MANISH"])

In [10]:
s2

SONU      78
MONI      98
RADHA     67
VIRAT     78
SHAAM     87
VIJAY     87
MANISH    95
dtype: int64

In [11]:
s2["SONU"]

np.int64(78)

In [12]:
S3 = pd.Series([ 99, 98, 97, 96, 95, 94, 98], index =['Rohit', 'Moni', 'Vikas', 'John', 'Harry', 'Dirko', 'Sonu'] )

In [13]:
S3

Rohit    99
Moni     98
Vikas    97
John     96
Harry    95
Dirko    94
Sonu     98
dtype: int64

In [14]:
type(S3)

pandas.core.series.Series

In [17]:
# Data fram = 2D labeled table
data = {
    'Name' : ['sonu', 'monu', 'shivani', 'radha'],
    'Age' : [35, 23, 54, 32],
    'City' : ['Delhi', 'Mumbai', 'Rajisthan', 'Uttar pardash'],
    'Region' : ['Indian', 'Indian', 'Indian','Indian']
    
}

In [19]:
pd.DataFrame(data)

      Name  Age           City  Region
0     sonu   35          Delhi  Indian
1     monu   23         Mumbai  Indian
2  shivani   54      Rajisthan  Indian
3    radha   32  Uttar pardash  Indian

In [21]:
df = pd.DataFrame(data)

In [22]:
df

      Name  Age           City  Region
0     sonu   35          Delhi  Indian
1     monu   23         Mumbai  Indian
2  shivani   54      Rajisthan  Indian
3    radha   32  Uttar pardash  Indian

In [25]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
df.columns

Index(['Name', 'Age', 'City', 'Region'], dtype='object')