In [2]:
import pandas as pd

In [3]:
data = [["sonu", 56, "Govt Boys", "Pass"],["vijay", 76, "Govt Boys", "Pass"],["raju", 90, "Govt Boys", "Pass"],
        ["rani", 78, "Govt Girls", "Pass"], ["ajay", 65, "Govt Boys", "Pass"]]

In [5]:
data

[['sonu', 56, 'Govt Boys', 'Pass'],
 ['vijay', 76, 'Govt Boys', 'Pass'],
 ['raju', 90, 'Govt Boys', 'Pass'],
 ['rani', 78, 'Govt Girls', 'Pass'],
 ['ajay', 65, 'Govt Boys', 'Pass']]

In [10]:
pd.DataFrame(data, columns=["Name", "Marks", "School", "Result"])

    Name  Marks      School Result
0   sonu     56   Govt Boys   Pass
1  vijay     76   Govt Boys   Pass
2   raju     90   Govt Boys   Pass
3   rani     78  Govt Girls   Pass
4   ajay     65   Govt Boys   Pass

In [11]:
data = {"A": [44, 56, 78],"B":[36, 65, 76]}

In [12]:
data

{'A': [44, 56, 78], 'B': [36, 65, 76]}

In [14]:
pd.DataFrame(data)

    A   B
0  44  36
1  56  65
2  78  76

In [18]:
import numpy as np

In [26]:
arr = np.array([[5, 1],[10, 5]])

In [27]:
df = pd.DataFrame(arr, columns =["A", "B"])

In [28]:
df

    A  B
0   5  1
1  10  5

In [35]:
pd.read_excel("Excel.xlsx")

     Name   Class  Marks School Result
0     Sonu   10th     76    USS   Pass
1     Monu  12th      87    FIS   Pass
2  Shivani   11th     33    GIS   Fail
3     Raju   9th      54  USSIS   Pass
4    Vikey  11th      76   GBSS   Pass
5    Vijay  11th      24   SKVS   Fail
6    Raja   11th      54    JUS   Pass
7    Guddu   10th     99    HUS   Pass
8   Ashish  12th      78   SUIS   Pass
9    Rohan  12th      87   LOIS   Pass

In [37]:
df = pd.read_excel("Excel.xlsx")

In [38]:
df

     Name   Class  Marks School Result
0     Sonu   10th     76    USS   Pass
1     Monu  12th      87    FIS   Pass
2  Shivani   11th     33    GIS   Fail
3     Raju   9th      54  USSIS   Pass
4    Vikey  11th      76   GBSS   Pass
5    Vijay  11th      24   SKVS   Fail
6    Raja   11th      54    JUS   Pass
7    Guddu   10th     99    HUS   Pass
8   Ashish  12th      78   SUIS   Pass
9    Rohan  12th      87   LOIS   Pass

In [40]:
df = pd.read_csv("data.csv")

In [41]:
df

     Name   Class  Marks School Result
0     Sonu   10th     76    USS   Pass
1     Monu  12th      87    FIS   Pass
2  Shivani   11th     33    GIS   Fail
3     Raju   9th      54  USSIS   Pass
4    Vikey  11th      76   GBSS   Pass
5    Vijay  11th      24   SKVS   Fail
6    Raja   11th      54    JUS   Pass
7    Guddu   10th     99    HUS   Pass
8   Ashish  12th      78   SUIS   Pass
9    Rohan  12th      87   LOIS   Pass

In [51]:
df = pd.read_json("data.json.txt")

In [52]:
df

    Name    lang
0  harry  Python
1   john    java

In [58]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [59]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [67]:
# EDA(Exploratory data Analysis)

In [60]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [61]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [63]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [65]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [66]:
df.shape

(244, 7)