In [3]:
import pandas as pd

In [5]:
df = pd.read_excel("Excel2.xlsx")

In [8]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [9]:
df['Actor']

0        Shah Rukh khan
1           Salman khan
2            Aamir khan
3         Ranbir kapoor
4         Ranveer singh
5     Ayushmann khurann
6          Rajkumar Rao
7      Hritithik Roshan
8          Akashy kumar
9          Kartik Aryan
10        Varun Dhawaan
11        Vicky kaushal
Name: Actor, dtype: object

In [11]:
df['Actor'][7]

'Hritithik Roshan'

In [13]:
type(df['Actor'])

pandas.core.series.Series

In [15]:
df[['Actor', 'IMDp']]

                Actor  IMDp
0      Shah Rukh khan   7.2
1         Salman khan   6.0
2          Aamir khan   8.4
3       Ranbir kapoor   5.6
4       Ranveer singh   7.0
5   Ayushmann khurann   8.3
6        Rajkumar Rao   7.5
7    Hritithik Roshan   6.5
8        Akashy kumar   7.0
9        Kartik Aryan   5.8
10      Varun Dhawaan   6.1
11      Vicky kaushal   8.2

In [17]:
df.loc[0]

Actor                    Shah Rukh khan
Film                             Pathan
Year                               2023
Genre                           Action
Boxoffice(INR Crore)               1050
IMDp                                7.2
Name: 0, dtype: object

In [18]:
df.iloc[1]

Actor                         Salman khan
Film                     Tiger Zinda hai
Year                                 2017
Genre                             Action
Boxoffice(INR Crore)                  760
IMDp                                  6.0
Name: 1, dtype: object

In [20]:
df.loc[8, 'Film']

'Good News'

In [25]:
df.iloc[8, 1]

'Good News'

In [28]:
df.loc[0:5, ["Actor", "Film", "Year"]]

               Actor              Film  Year
0     Shah Rukh khan            Pathan  2023
1        Salman khan  Tiger Zinda hai   2017
2         Aamir khan            Dangal  2016
3      Ranbir kapoor       Brahmasatre  2022
4      Ranveer singh         Padmaavat  2018
5  Ayushmann khurann         Andhadhan  2018

In [29]:
df.iloc[0:5, 0:5]

            Actor              Film  Year       Genre  Boxoffice(INR Crore)
0  Shah Rukh khan            Pathan  2023     Action                    1050
1     Salman khan  Tiger Zinda hai   2017     Action                     760
2      Aamir khan            Dangal  2016   Biography                   2024
3   Ranbir kapoor       Brahmasatre  2022     Fantacy                    431
4   Ranveer singh         Padmaavat  2018  Historical                    585

In [32]:
df.at[0, 'Actor']

'Shah Rukh khan'

In [34]:
df.iat[0, 3]

'Action '

In [38]:
df[df['IMDp']>7]

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
2,Aamir khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [39]:
df[df['IMDp']>7]['Film']

0        Pathan
2        Dangal
5     Andhadhan
6         Stree
11          Uri
Name: Film, dtype: object

In [43]:
df[(df['IMDp']>6) & (df['Year']>=2018)]

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [42]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [44]:
df.query("Year > 2019 and IMDp >7")

            Actor    Film  Year    Genre  Boxoffice(INR Crore)   IMDp
0  Shah Rukh khan  Pathan  2023  Action                    1050   7.2

In [46]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [59]:
df2 = df[['Actor', 'IMDp']]

In [60]:
df2

                Actor  IMDp
0      Shah Rukh khan   7.2
1         Salman khan   6.0
2          Aamir khan   8.4
3       Ranbir kapoor   5.6
4       Ranveer singh   7.0
5   Ayushmann khurann   8.3
6        Rajkumar Rao   7.5
7    Hritithik Roshan   6.5
8        Akashy kumar   7.0
9        Kartik Aryan   5.8
10      Varun Dhawaan   6.1
11      Vicky kaushal   8.2

In [61]:
df2.loc[0, 'Actor'] = 'Rohit Sharama' #change the name of the list condit.

In [62]:
df2

                Actor  IMDp
0       Rohit Sharama   7.2
1         Salman khan   6.0
2          Aamir khan   8.4
3       Ranbir kapoor   5.6
4       Ranveer singh   7.0
5   Ayushmann khurann   8.3
6        Rajkumar Rao   7.5
7    Hritithik Roshan   6.5
8        Akashy kumar   7.0
9        Kartik Aryan   5.8
10      Varun Dhawaan   6.1
11      Vicky kaushal   8.2

In [63]:
df2

                Actor  IMDp
0       Rohit Sharama   7.2
1         Salman khan   6.0
2          Aamir khan   8.4
3       Ranbir kapoor   5.6
4       Ranveer singh   7.0
5   Ayushmann khurann   8.3
6        Rajkumar Rao   7.5
7    Hritithik Roshan   6.5
8        Akashy kumar   7.0
9        Kartik Aryan   5.8
10      Varun Dhawaan   6.1
11      Vicky kaushal   8.2

In [64]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [69]:
df.at[6, "Film"]

'Stree'