In [2]:
import pandas as pd

In [26]:
df = pd.read_csv("data_cleaning_sample.csv")

In [7]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [8]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False  False  False   False  False      False
4   True  False  False   False  False       True

In [9]:
df.isnull().sum()

Name         1
Age          1
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [11]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  David  22.0       Mumbai      M  david@example.com  12/11/2019

In [14]:
df.fillna('-')

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie     -        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4        -  28.0        Delhi      F     eve@domain.com           -

In [20]:
df['Age'].fillna(df['Age'].mean())

0    25.00
1    26.25
2    30.00
3    22.00
4    28.00
Name: Age, dtype: float64

In [21]:
df.fillna(method = "ffill")

C:\Users\manis\AppData\Local\Temp\ipykernel_6264\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4    David  28.0        Delhi      F     eve@domain.com  12/11/2019

In [23]:
df.fillna(method= "bfill")

C:\Users\manis\AppData\Local\Temp\ipykernel_6264\3528466224.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method= "bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [25]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4    David  28.0        Delhi      F     eve@domain.com  12/11/2019

In [37]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6    David  22.0       Mumbai      M  david@example.com  12/11/2019
7      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
8    David  22.0       Mumbai      M  david@example.com  12/11/2019

In [34]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [36]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [39]:
df.duplicated(subset = ["Name", "City"])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [40]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6    David  22.0       Mumbai      M  david@example.com  12/11/2019
7      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
8    David  22.0       Mumbai      M  david@example.com  12/11/2019

In [43]:
df['Name'].str.lower() #its convert of the letter into small litter

0      alice
1    charlie
2        bob
3      david
4        NaN
5        bob
6      david
7        bob
8      david
Name: Name, dtype: object

In [45]:
df["Name"].str.upper() #all the name letter convert into upper form

0      ALICE
1    CHARLIE
2        BOB
3      DAVID
4        NaN
5        BOB
6      DAVID
7        BOB
8      DAVID
Name: Name, dtype: object

In [47]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6    David  22.0       Mumbai      M  david@example.com  12/11/2019
7      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
8    David  22.0       Mumbai      M  david@example.com  12/11/2019

In [51]:
df["City"].str.contains("Delhi", case=False) #checking the if delhi is in city name in case = True/False

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8    False
Name: City, dtype: bool

In [52]:
type(df["City"].str.contains("Delhi", case=False))

pandas.core.series.Series

In [55]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3    [david, example.com]
4       [eve, domain.com]
5      [bob, example.com]
6    [david, example.com]
7      [bob, example.com]
8    [david, example.com]
Name: Email, dtype: object

In [56]:
type(df["Email"].str.split("@")[0])

list

In [57]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6    David  22.0       Mumbai      M  david@example.com  12/11/2019
7      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
8    David  22.0       Mumbai      M  david@example.com  12/11/2019

In [58]:
df2 = df.dropna().copy()

In [60]:
df2['Age'] = df2['Age'].astype(int)

In [61]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12/11/2019
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
6  David   22       Mumbai      M  david@example.com  12/11/2019
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
8  David   22       Mumbai      M  david@example.com  12/11/2019

In [62]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12/11/2019
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
6  David   22       Mumbai      M  david@example.com  12/11/2019
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
8  David   22       Mumbai      M  david@example.com  12/11/2019

In [66]:
df2.drop_duplicates()

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12/11/2019

In [67]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12/11/2019
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
6  David   22       Mumbai      M  david@example.com  12/11/2019
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
8  David   22       Mumbai      M  david@example.com  12/11/2019

In [68]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       7 non-null      object
 1   Age        7 non-null      int64
 2   City       7 non-null      object
 3   Gender     7 non-null      object
 4   Email      7 non-null      object
 5   Join Date  7 non-null      object
dtypes: int64(1), object(5)
memory usage: 392.0+ bytes

In [75]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12/11/2019
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
6  David   22       Mumbai      M  david@example.com  12/11/2019
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
8  David   22       Mumbai      M  david@example.com  12/11/2019

In [76]:
df2['Age Group'] = df2['Age'].apply(lambda x: 'Adult' if x >= 25 else 'Minor')

In [77]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com    1/5/2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  David   22       Mumbai      M  david@example.com  12/11/2019     Minor
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
6  David   22       Mumbai      M  david@example.com  12/11/2019     Minor
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
8  David   22       Mumbai      M  david@example.com  12/11/2019     Minor

In [85]:
def isminor(x):
    return "Audlt" if x >= 25 else "Minor"

df2['Age Group'] = df2['Age'].apply(isminor)

In [87]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com    1/5/2021     Audlt
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Audlt
3  David   22       Mumbai      M  david@example.com  12/11/2019     Minor
5    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Audlt
6  David   22       Mumbai      M  david@example.com  12/11/2019     Minor
7    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Audlt
8  David   22       Mumbai      M  david@example.com  12/11/2019     Minor

In [ ]:
gender_map = {"M": "Male", "F": "Female", "O": "Other"}
df2["Gender"] = df2["gender"].map(gender_map)

In [100]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York    NaN  alice@example.com    1/5/2021     Audlt
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Audlt
3  David   22       Mumbai    NaN  david@example.com  12/11/2019     Minor
5    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Audlt
6  David   22       Mumbai    NaN  david@example.com  12/11/2019     Minor
7    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Audlt
8  David   22       Mumbai    NaN  david@example.com  12/11/2019     Minor

In [107]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12/11/2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6    David  22.0       Mumbai      M  david@example.com  12/11/2019
7      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
8    David  22.0       Mumbai      M  david@example.com  12/11/2019

In [108]:
df = df["City"].replace({"Mumbai": "New Delhi"})

In [109]:
df

0       New York
1          Delhi
2    Los Angeles
3      New Delhi
4          Delhi
5    Los Angeles
6      New Delhi
7    Los Angeles
8      New Delhi
Name: City, dtype: object

In [110]:
df

0       New York
1          Delhi
2    Los Angeles
3      New Delhi
4          Delhi
5    Los Angeles
6      New Delhi
7    Los Angeles
8      New Delhi
Name: City, dtype: object