In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("Excel3.csv")

In [54]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [55]:
df.sort_values("Year")

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
2,Aamir khan,Dangal,2016,Biography,2024,8.4
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
11,Vicky kaushal,Uri,2019,Action,343,8.2
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2

In [56]:
df.sort_values("Year", ascending=False)

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
8,Akashy kumar,Good News,2019,Comedy,318,7.0
11,Vicky kaushal,Uri,2019,Action,343,8.2
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
2,Aamir khan,Dangal,2016,Biography,2024,8.4

In [57]:
df.sort_values("IMDp")

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
7,Hritithik Roshan,War,2018,Action,475,6.5
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
8,Akashy kumar,Good News,2019,Comedy,318,7.0
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky kaushal,Uri,2019,Action,343,8.2
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
2,Aamir khan,Dangal,2016,Biography,2024,8.4

In [58]:
df.sort_values("IMDp", ascending=False)

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
2,Aamir khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
11,Vicky kaushal,Uri,2019,Action,343,8.2
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
8,Akashy kumar,Good News,2019,Comedy,318,7.0
7,Hritithik Roshan,War,2018,Action,475,6.5
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6

In [59]:
df2 = df.sort_values(["Year", "IMDp"]).copy()

In [60]:
df2.reset_index()

,index,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,2,Aamir khan,Dangal,2016,Biography,2024,8.4
1,1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
3,7,Hritithik Roshan,War,2018,Action,475,6.5
4,4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
6,5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
7,8,Akashy kumar,Good News,2019,Comedy,318,7.0
8,11,Vicky kaushal,Uri,2019,Action,343,8.2
9,3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
10,9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
11,0,Shah Rukh khan,Pathan,2023,Action,1050,7.2

In [61]:
# df2.reset_index(drop=True)

In [62]:
df2 #no change of the old data frame

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
2,Aamir khan,Dangal,2016,Biography,2024,8.4
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
7,Hritithik Roshan,War,2018,Action,475,6.5
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
8,Akashy kumar,Good News,2019,Comedy,318,7.0
11,Vicky kaushal,Uri,2019,Action,343,8.2
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2

In [63]:
# df2.reset_index(drop= True, inplace=True) #no need to run .copy() funtion

# SORTING IN INDEX

In [64]:
df2

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
2,Aamir khan,Dangal,2016,Biography,2024,8.4
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
7,Hritithik Roshan,War,2018,Action,475,6.5
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
8,Akashy kumar,Good News,2019,Comedy,318,7.0
11,Vicky kaushal,Uri,2019,Action,343,8.2
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2

In [65]:
df2.sort_index()

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [84]:
df2["Rank"] = df2["IMDp"].rank(ascending = False, method= "dense")

In [88]:
df2.sort_values("Rank")

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp,Rank
2,Aamir khan,Dangal,2016,Biography,2024,8.4,1.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3,2.0
11,Vicky kaushal,Uri,2019,Action,343,8.2,3.0
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2,5.0
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0,6.5
7,Hritithik Roshan,War,2018,Action,475,6.5,8.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1,9.0
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0,10.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8,11.0
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6,12.0

In [89]:
df2

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp,Rank
2,Aamir khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0,10.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1,9.0
7,Hritithik Roshan,War,2018,Action,475,6.5,8.0
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0,6.5
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3,2.0
8,Akashy kumar,Good News,2019,Comedy,318,7.0,6.5
11,Vicky kaushal,Uri,2019,Action,343,8.2,3.0
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6,12.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8,11.0
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2,5.0

In [117]:
df2.rename(columns = {"Actor" : "Superster"}, inplace = True)

In [118]:
df2

,Rank,Genre,Film,Year,IMDp,Boxoffice(INR Crore),Superstar
2,Aamir khan,Dangal,2016,Biography,2024,8.4,1.0
salman,Salman khan,Tiger Zinda hai,2017,Action,760,6.0,10.0
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1,9.0
7,Hritithik Roshan,War,2018,Action,475,6.5,8.0
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0,6.5
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3,2.0
8,Akashy kumar,Good News,2019,Comedy,318,7.0,6.5
11,Vicky kaushal,Uri,2019,Action,343,8.2,3.0
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6,12.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8,11.0
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2,5.0

In [119]:
df

,Actor,Film,Year,Genre,Boxoffice(INR Crore),IMDp
0,Shah Rukh khan,Pathan,2023,Action,1050,7.2
1,Salman khan,Tiger Zinda hai,2017,Action,760,6.0
2,Aamir khan,Dangal,2016,Biography,2024,8.4
3,Ranbir kapoor,Brahmasatre,2022,Fantacy,431,5.6
4,Ranveer singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann khurann,Andhadhan,2018,Thriller,111,8.3
6,Rajkumar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hritithik Roshan,War,2018,Action,475,6.5
8,Akashy kumar,Good News,2019,Comedy,318,7.0
9,Kartik Aryan,Bhool bhulaiya,2022,Horror Comedy,266,5.8
10,Varun Dhawaan,Badri ki dhulaniya,2017,Romantic comedy,201,6.1
11,Vicky kaushal,Uri,2019,Action,343,8.2

In [ ]:
df = df[["Year", "Actor", "Film", "Genre", "IMDp","Boxoffice(INR Crore)"]]