In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [6]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [9]:
pd.merge(employees, departments, on="DeptID")#inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
pd.merge(employees, departments, on="DeptID", how="left")#left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
pd.merge(employees, departments, on="DeptID", how= "right")#right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees, departments, on="DeptID", how= "outer")#outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [19]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score": [908, 980]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age": [34, 22]})

pd.concat([df1, df2])

      Name  Score   Age
0    Alice  908.0   NaN
1      Bob  980.0   NaN
0  Charlie    NaN  34.0
1    David    NaN  22.0

In [16]:
df1

    Name
0  Alice
1    Bob

In [17]:
df2

      Name
0  Charlie
1    David

In [20]:
pd.concat([df1, df2], axis=1)

    Name  Score     Name  Age
0  Alice    908  Charlie   34
1    Bob    980    David   22

In [23]:
df1 = pd.DataFrame({"Name": ["Sonu", "Raj", "Kumar"],"Roll no":[88, 90, 95]})
df2 = pd.DataFrame({"Name": ["Rahul", "Radha"], "Age":[56, 45]})

In [22]:
df1

    Name  Score
0  Alice    908
1    Bob    980

In [24]:
df2

    Name  Age
0  Rahul   56
1  Radha   45

In [25]:
pd.concat([df1, df2], axis=1)

    Name  Roll no   Name   Age
0   Sonu       88  Rahul  56.0
1    Raj       90  Radha  45.0
2  Kumar       95    NaN   NaN

In [27]:
pd.concat([df1, df2])

    Name  Roll no   Age
0   Sonu     88.0   NaN
1    Raj     90.0   NaN
2  Kumar     95.0   NaN
0  Rahul      NaN  56.0
1  Radha      NaN  45.0